import { config } from "dotenv";
config({ path: ".env.local" });

import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "./schema";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql, { schema });

type SeedSubject = {
  slug: string;
  name: string;
  examBoard: string;
  specCode?: string;
  colorTag: string;
  topics: string[];
};

const seedSubjects: SeedSubject[] = [
  {
    slug: "accounting",
    name: "Accounting",
    examBoard: "AQA A-level",
    specCode: "7127",
    colorTag: "#265BF6",
    topics: [
      "An introduction to the role of the accountant in business",
      "Types of business organisation",
      "The double entry model",
      "Verification of accounting records",
      "Accounting concepts used in the preparation of accounting records",
      "Preparation of financial statements of sole traders",
      "Limited company accounts",
      "Analysis and evaluation of financial information",
      "Budgeting",
      "Marginal costing",
      "Standard costing and variance analysis",
      "Absorption and activity based costing",
      "Capital investment appraisal",
      "Accounting for organisations with incomplete records",
      "Partnership accounts",
      "Accounting for limited companies",
      "Interpretation, analysis and communication of accounting information",
      "The impact of ethical considerations",
    ],
  },
  {
    slug: "economics",
    name: "Economics",
    examBoard: "AQA A-level",
    specCode: "7136",
    colorTag: "#1CA789",
    topics: [
      "Economic methodology and the economic problem",
      "Individual economic decision making",
      "Price determination in a competitive market",
      "Production, costs and revenue",
      "Perfect competition, imperfectly competitive markets and monopoly",
      "The labour market",
      "Distribution of income and wealth: poverty and inequality",
      "Market mechanism, market failure and government intervention",
      "Measurement of macroeconomic performance and objectives",
      "How the macroeconomy works: circular flow, AD/AS analysis",
      "Economic performance",
      "Financial markets and monetary policy",
      "Fiscal policy and supply-side policies",
      "The international economy",
    ],
  },
  {
    slug: "business",
    name: "Business",
    examBoard: "Pearson BTEC (assumed: Extended Certificate)",
    colorTag: "#F6A623",
    topics: [
      "Unit 1: Exploring business",
      "Unit 2: Developing a marketing campaign",
      "Unit 3: Personal and business finance",
    ],
  },
  {
    slug: "business-studies",
    name: "Business Studies",
    examBoard: "AQA A-level",
    specCode: "7132",
    colorTag: "#E08E24",
    topics: [
      "What is business?",
      "Managers, leadership and decision making",
      "Decision making to improve marketing performance",
      "Decision making to improve operational performance",
      "Decision making to improve financial performance",
      "Decision making to improve human resource performance",
      "Analysing the strategic position of a business",
      "Choosing strategic direction",
      "Strategic methods: how to pursue strategies",
      "Managing strategic change",
    ],
  },
  {
    slug: "ancient-history",
    name: "Ancient History",
    examBoard: "OCR A-level",
    specCode: "H407",
    colorTag: "#9B6B43",
    topics: [
      "Relations between Greek states and between Greek and non-Greek states, 492–404 BC",
      "The Society and Politics of Sparta, 478–404 BC",
      "The Culture and Politics of Athens, c.460–399 BC",
      "The Rise of Macedon, c.359–323 BC",
      "The Julio-Claudian Emperors, 31 BC–AD 68",
      "The Breakdown of the Late Republic, 88–31 BC",
      "The Flavians, AD 68–96",
      "Ruling Roman Britain, AD 43–c.128",
    ],
  },
  {
    slug: "classical-civilisation",
    name: "Classical Civilisation",
    examBoard: "OCR A-level",
    specCode: "H408",
    colorTag: "#7A5C99",
    topics: [
      "The World of the Hero (Homer's Iliad or Odyssey + Virgil's Aeneid)",
      "Greek Theatre",
      "Imperial Image",
      "Invention of the Barbarian",
      "Greek Art",
      "Greek Religion",
      "Love and Relationships",
      "Politics of the Late Republic",
      "Democracy and the Athenians",
    ],
  },
  {
    slug: "history",
    name: "History",
    examBoard: "AQA A-level",
    specCode: "7042",
    colorTag: "#B34747",
    topics: [
      "1A The Age of the Crusades, c1071–1204",
      "1B Spain in the Age of Discovery, 1469–1598",
      "1C The Tudors: England, 1485–1603",
      "1D Stuart Britain and the Crisis of Monarchy, 1603–1702",
      "1E Russia in the Age of Absolutism and Enlightenment, 1682–1796",
      "1F Industrialisation and the people: Britain, c1783–1885",
      "1G Challenge and transformation: Britain, c1851–1964",
      "1H Tsarist and Communist Russia, 1855–1964",
      "1J The British Empire, c1857–1967",
      "1K The making of a Superpower: USA, 1865–1975",
      "1L The quest for political stability: Germany, 1871–1991",
      "2A Royal Authority and the Angevin Kings, 1154–1216",
      "2B The Wars of the Roses, 1450–1499",
      "2C The Reformation in Europe, c1500–1564",
      "2D Religious conflict and the Church in England, c1529–c1570",
      "2E The English Revolution, 1625–1660",
      "2F The Sun King: Louis XIV, France and Europe, 1643–1715",
      "2G The Birth of the USA, 1760–1801",
      "2H France in Revolution, 1774–1815",
      "2J America: A Nation Divided, c1845–1877",
      "2K International Relations and Global Conflict, c1890–1941",
      "2L Italy and Fascism, c1900–1945",
      "2M Wars and Welfare: Britain in Transition, 1906–1957",
      "2N Revolution and dictatorship: Russia, 1917–1953",
      "2O Democracy and Nazism: Germany, 1918–1945",
      "2P The Transformation of China, 1936–1997",
      "2Q The American Dream: reality and illusion, 1945–1980",
      "2R The Cold War, c1945–1991",
      "2S The Making of Modern Britain, 1951–2007",
      "2T The Crisis of Communism: The USSR and the Soviet Empire, 1953–2000",
      "Component 3: Historical Investigation (student-chosen title)",
    ],
  },
  {
    slug: "history-of-art",
    name: "History of Art",
    examBoard: "Pearson Edexcel A-level",
    specCode: "9HT0",
    colorTag: "#C2578A",
    topics: [
      "Visual Analysis (painting, sculpture, architecture)",
      "Nature in art and architecture",
      "Identities in art and architecture",
      "War in art and architecture",
      "Invention and illusion: the Renaissance in Italy (1420–1520)",
      "Power and persuasion: the Baroque in Catholic Europe (1597–1685)",
      "Rebellion and revival: the British and French Avant-Garde (1848–99)",
      "Brave new world: Modernism in Europe (1900–39)",
      "Pop life: British and American contemporary art and architecture (1960–2015)",
    ],
  },
  {
    slug: "law",
    name: "Law",
    examBoard: "AQA A-level",
    specCode: "7162",
    colorTag: "#3B4C99",
    topics: [
      "Nature of law: legal rules, sources of law, law and society, law and morality, law and justice",
      "The rule of law",
      "Parliamentary law making and delegated legislation",
      "Statutory interpretation",
      "Judicial precedent",
      "Law reform (the Law Commission)",
      "Law making and the European Union",
      "The civil courts and other forms of dispute resolution",
      "The criminal courts and lay people",
      "Legal personnel and the judiciary",
      "Access to justice and funding",
      "Criminal law: general elements of liability",
      "Criminal law: fatal offences against the person",
      "Criminal law: non-fatal offences against the person",
      "Criminal law: property offences and attempt",
      "Criminal law: defences",
      "Tort: liability in negligence",
      "Tort: occupiers' liability, nuisance and vicarious liability",
      "Tort: defences and remedies",
      "Law of contract: formation, terms and exclusion clauses",
      "Law of contract: vitiating factors, discharge and remedies",
      "Human rights: origins, status in UK law, and substantive rights",
    ],
  },
  {
    slug: "philosophy",
    name: "Philosophy",
    examBoard: "AQA A-level",
    specCode: "7172",
    colorTag: "#5D6470",
    topics: [
      "What is knowledge?",
      "Perception as a source of knowledge",
      "Reason as a source of knowledge",
      "The limits of knowledge",
      "Normative ethical theories",
      "Applied ethics",
      "Meta-ethics",
      "The concept and nature of 'God'",
      "Arguments relating to the existence of God",
      "Religious language",
      "What do we mean by 'mind'?",
      "Dualist theories",
      "Physicalist theories",
      "Functionalism",
    ],
  },
  {
    slug: "politics",
    name: "Politics",
    examBoard: "AQA A-level",
    specCode: "7152",
    colorTag: "#2E7D6B",
    topics: [
      "The nature and sources of the British Constitution",
      "The structure and role of Parliament",
      "The Prime Minister and cabinet",
      "The judiciary",
      "Devolution",
      "Democracy and participation",
      "Elections and referendums",
      "Political parties (UK)",
      "Pressure groups (UK)",
      "The European Union",
      "The constitutional framework of US government",
      "The legislative branch of government: Congress",
      "The executive branch of government: President",
      "The judicial branch of government (USA)",
      "The electoral process and direct democracy (USA)",
      "Political parties (USA)",
      "Pressure groups (USA)",
      "Civil rights (USA)",
      "Comparative politics",
      "Political ideas: Liberalism, Conservatism, Socialism, plus one further ideology",
    ],
  },
  {
    slug: "religious-studies",
    name: "Religious Studies / Theology",
    examBoard: "AQA A-level",
    specCode: "7062",
    colorTag: "#8A6D3B",
    topics: [
      "Arguments for the existence of God",
      "Evil and suffering",
      "Religious experience",
      "Religious language",
      "Miracles",
      "Self and life after death",
      "Ethical theories",
      "Issues of human life and death",
      "Issues of animal life and death",
      "Introduction to meta-ethics",
      "Free will and moral responsibility",
      "Conscience",
      "Bentham and Kant",
      "Sources of wisdom and authority (chosen religion)",
      "God/gods/ultimate reality (chosen religion)",
      "Self, death and the afterlife (chosen religion)",
      "Good conduct and key moral principles (chosen religion)",
      "Expression of religious identity (chosen religion)",
      "Religion, gender and sexuality (chosen religion)",
      "Religion and science (chosen religion)",
      "Religion and secularisation (chosen religion)",
      "Religion and religious pluralism (chosen religion)",
      "Dialogue between philosophy of religion and religion",
      "Dialogue between ethical studies and religion",
    ],
  },
  {
    slug: "sociology",
    name: "Sociology",
    examBoard: "AQA A-level",
    specCode: "7192",
    colorTag: "#B0559C",
    topics: [
      "Education",
      "Methods in Context",
      "Culture and Identity (optional topic)",
      "Families and Households (optional topic)",
      "Health (optional topic)",
      "Work, Poverty and Welfare (optional topic)",
      "Beliefs in Society (optional topic)",
      "Global Development (optional topic)",
      "The Media (optional topic)",
      "Stratification and Differentiation (optional topic)",
      "Crime and Deviance",
      "Theory and Methods",
    ],
  },
  {
    slug: "geography",
    name: "Geography",
    examBoard: "AQA A-level",
    specCode: "7037",
    colorTag: "#3F8F5C",
    topics: [
      "Water and carbon cycles",
      "Hot desert systems and landscapes",
      "Coastal systems and landscapes",
      "Glacial systems and landscapes",
      "Hazards",
      "Ecosystems under stress",
      "Global systems and global governance",
      "Changing places",
      "Contemporary urban environments",
      "Population and the environment",
      "Resource security",
    ],
  },
  {
    slug: "biology",
    name: "Biology",
    examBoard: "AQA A-level",
    specCode: "7402",
    colorTag: "#2F9E44",
    topics: [
      "Biological molecules",
      "Cells",
      "Organisms exchange substances with their environment",
      "Genetic information, variation and relationships between organisms",
      "Energy transfers in and between organisms",
      "Organisms respond to changes in their internal and external environments",
      "Genetics, populations, evolution and ecosystems",
      "The control of gene expression",
    ],
  },
  {
    slug: "chemistry",
    name: "Chemistry",
    examBoard: "AQA A-level",
    specCode: "7405",
    colorTag: "#1C7ED6",
    topics: [
      "Atomic structure",
      "Amount of substance",
      "Bonding",
      "Energetics",
      "Kinetics",
      "Chemical equilibria, Le Chatelier's principle and Kc",
      "Oxidation, reduction and redox equations",
      "Thermodynamics",
      "Rate equations",
      "Equilibrium constant Kp for homogeneous systems",
      "Electrode potentials and electrochemical cells",
      "Acids and bases",
      "Periodicity",
      "Group 2, the alkaline earth metals",
      "Group 7(17), the halogens",
      "Properties of Period 3 elements and their oxides",
      "Transition metals",
      "Reactions of ions in aqueous solution",
      "Introduction to organic chemistry",
      "Alkanes",
      "Halogenoalkanes",
      "Alkenes",
      "Alcohols",
      "Organic analysis",
      "Optical isomerism",
      "Aldehydes and ketones",
      "Carboxylic acids and derivatives",
      "Aromatic chemistry",
      "Amines",
      "Polymers",
      "Amino acids, proteins and DNA",
      "Organic synthesis",
      "Nuclear magnetic resonance spectroscopy",
      "Chromatography",
    ],
  },
  {
    slug: "computer-science",
    name: "Computer Science",
    examBoard: "AQA A-level",
    specCode: "7517",
    colorTag: "#0B7285",
    topics: [
      "Fundamentals of programming",
      "Fundamentals of data structures",
      "Fundamentals of algorithms",
      "Theory of computation",
      "Fundamentals of data representation",
      "Fundamentals of computer systems",
      "Fundamentals of computer organisation and architecture",
      "Consequences of uses of computing",
      "Fundamentals of communication and networking",
      "Fundamentals of databases",
      "Big Data",
      "Fundamentals of functional programming",
      "Systematic approach to problem solving",
      "Non-exam assessment – the computing practical project",
    ],
  },
  {
    slug: "electronics",
    name: "Electronics",
    examBoard: "WJEC Eduqas A-level",
    specCode: "A490QS",
    colorTag: "#495057",
    topics: [
      "System synthesis",
      "DC electrical circuits",
      "Input and output sub-systems",
      "Energy and power",
      "Semiconductor components",
      "Logic systems",
      "Operational amplifiers",
      "Signal conversion",
      "AC circuits and passive filters",
      "Communications systems",
      "Wireless transmission",
      "Instrumentation systems",
      "Timing circuits",
      "Sequential logic systems",
      "Microcontrollers",
      "Digital communications",
      "Optical communication",
      "Mains power supply systems",
      "High power switching systems",
      "Audio systems",
    ],
  },
  {
    slug: "environmental-science",
    name: "Environmental Science",
    examBoard: "AQA A-level",
    specCode: "7447",
    colorTag: "#66A80F",
    topics: [
      "The living environment",
      "The physical environment",
      "Energy resources",
      "Pollution",
      "Biological resources",
      "Sustainability",
      "Research methods",
    ],
  },
  {
    slug: "geology",
    name: "Geology",
    examBoard: "WJEC Eduqas A-level",
    specCode: "A480QS",
    colorTag: "#A0730B",
    topics: [
      "Elements, minerals and rocks",
      "Surface and internal processes of the rock cycle",
      "Time and change",
      "Earth structure and global tectonics",
      "Rock forming processes",
      "Rock deformation",
      "Past life and past climates",
      "Earth materials and natural resources",
      "Geohazards",
      "Geological map applications",
      "Quaternary geology (optional)",
      "Geological evolution of Britain (optional)",
      "Geology of the lithosphere (optional)",
    ],
  },
  {
    slug: "mathematics",
    name: "Mathematics",
    examBoard: "AQA A-level",
    specCode: "7357",
    colorTag: "#D9480F",
    topics: [
      "Proof",
      "Algebra and functions",
      "Coordinate geometry in the (x, y) plane",
      "Sequences and series",
      "Trigonometry",
      "Exponentials and logarithms",
      "Differentiation",
      "Integration",
      "Numerical methods",
      "Vectors",
      "Statistical sampling",
      "Data presentation and interpretation",
      "Probability",
      "Statistical distributions",
      "Statistical hypothesis testing",
      "Quantities and units in mechanics",
      "Kinematics",
      "Forces and Newton's laws",
      "Moments",
      "Use of data in statistics (large data set)",
    ],
  },
  {
    slug: "further-mathematics",
    name: "Further Mathematics",
    examBoard: "AQA A-level",
    specCode: "7367",
    colorTag: "#E8590C",
    topics: [
      "Proof",
      "Complex numbers",
      "Matrices",
      "Further algebra and functions",
      "Further calculus",
      "Further vectors",
      "Polar coordinates",
      "Hyperbolic functions",
      "Differential equations",
      "Numerical methods",
      "Optional application: Mechanics",
      "Optional application: Statistics",
      "Optional application: Discrete mathematics",
    ],
  },
  {
    slug: "physics",
    name: "Physics",
    examBoard: "AQA A-level",
    specCode: "7408",
    colorTag: "#4263EB",
    topics: [
      "Measurements and their errors",
      "Particles and radiation",
      "Waves",
      "Mechanics and materials",
      "Electricity",
      "Further mechanics and thermal physics",
      "Fields and their consequences",
      "Nuclear physics",
      "Astrophysics (optional)",
      "Medical physics (optional)",
      "Engineering physics (optional)",
      "Turning points in physics (optional)",
      "Electronics (optional)",
    ],
  },
  {
    slug: "psychology",
    name: "Psychology",
    examBoard: "AQA A-level",
    specCode: "7182",
    colorTag: "#AE3EC9",
    topics: [
      "Social influence",
      "Memory",
      "Attachment",
      "Clinical psychology and mental health",
      "Approaches in psychology",
      "Biopsychology",
      "Research methods",
      "Issues and debates in psychology",
      "Relationships (optional)",
      "Gender (optional)",
      "Cognition and development (optional)",
      "Schizophrenia (optional)",
      "Eating behaviour (optional)",
      "Stress (optional)",
      "Aggression (optional)",
      "Forensic psychology (optional)",
      "Addiction (optional)",
    ],
  },
  {
    slug: "statistics",
    name: "Statistics",
    examBoard: "Pearson Edexcel A-level",
    specCode: "9ST0",
    colorTag: "#F08C00",
    topics: [
      "Numerical measures, graphs and diagrams",
      "Probability",
      "Population and samples",
      "Introduction to probability distributions",
      "Binomial distribution",
      "Normal distribution",
      "Correlation and linear regression",
      "Introduction to hypothesis testing",
      "Contingency tables",
      "One and two sample non-parametric tests",
      "Bayes' theorem",
      "Probability distributions",
      "Experimental design",
      "Sampling, estimates and resampling",
      "Hypothesis testing, significance testing, confidence intervals and power",
      "Hypothesis testing for 1 and 2 samples",
      "Paired tests",
      "Exponential and Poisson distributions",
      "Goodness of fit",
      "Analysis of variance",
      "Effect size",
    ],
  },
];

async function main() {
  for (const subject of seedSubjects) {
    const [row] = await db
      .insert(schema.subjects)
      .values({
        slug: subject.slug,
        name: subject.name,
        examBoard: subject.examBoard,
        specCode: subject.specCode,
        colorTag: subject.colorTag,
        isSeeded: true,
      })
      .onConflictDoUpdate({
        target: schema.subjects.slug,
        set: {
          name: subject.name,
          examBoard: subject.examBoard,
          specCode: subject.specCode,
          colorTag: subject.colorTag,
        },
      })
      .returning();

    for (const [index, title] of subject.topics.entries()) {
      const existing = await db.query.topics.findFirst({
        where: (t, { eq, and }) =>
          and(eq(t.subjectId, row.id), eq(t.title, title)),
      });
      if (existing) continue;

      await db.insert(schema.topics).values({
        subjectId: row.id,
        title,
        orderIndex: index,
        isCustom: false,
      });
    }

    console.log(`Seeded ${subject.name} (${subject.topics.length} topics)`);
  }
}

main()
  .then(() => {
    console.log("Seed complete.");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
